# Generated by Django 4.1 on 2022-09-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='desciption',
            new_name='description',
        ),
    ]
